version: '3.8'

services:
  # 1. The Backend API
  backend:
    build: .
    container_name: abrar_api
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./processed_data:/app/processed

  # 2. The Frontend Dashboard
  frontend:
    image: nginx:alpine
    container_name: abrar_dashboard
    restart: always
    ports:
      - "8090:80"
    volumes:
      - ./dashboard.html:/usr/share/nginx/html/index.html
